import '@bdl/ui-kit/style.css';
import wasmUrl from 'manifold-3d/manifold.wasm?url';
import { loadManifold,bounds,assemblySeats,type Part } from '@bdl/geometry';
import { createViewer } from '@bdl/viewer';
import { toSTL,to3MF,download,slug } from '@bdl/export';
import { zipSync } from 'fflate';
import { appShell,section,slider,colorPicker,button,iconButton,panelFooter,readHashState,writeHashState,ICONS,el,segmented,toast,toggle } from '@bdl/ui-kit';
import { parseSvg,type SvgArtwork } from '../../coaster/src/svg.ts';
import { importArtwork } from '../../keycap/src/artwork.ts';
import { KEY_ICONS,keyIconSvg } from '../../keycap/src/icons.ts';
import { packPlates } from '../../box/src/parts.ts';
import { arrange,currentPlacement,type Placements } from '../../box/src/placement.ts';
import { build,type Design } from './geometry.ts';
import { DEFAULTS,sanitize,type Params } from './params.ts';
import { lettering,qrArtwork } from './artwork.ts';
const shell=appShell({title:'Portachiavi',intro:'Un nome, un simbolo o un messaggio da portare sempre con te.'});
let state=sanitize(readHashState(DEFAULTS)),uploaded:SvgArtwork|undefined,uploadedCover:SvgArtwork|undefined,extraArtwork:SvgArtwork|undefined,mountParts:Part[]=[],parts:Part[]=[],view='assembled',plate=0,selected:string|null=null;
let lastValid:Params={...state};
let plateSize=256,pinned:Placements={},shown:Part[]=[];
const viewer=createViewer(shell.stage,{onSelectPart:id=>{selected=id;},canMovePart:id=>view!=='assembled'||id.startsWith('Simbolo-')||(id.startsWith('Decorazione-')&&['name','initial','svg'].includes(state.model)),onMovePart:(id,dx,dy)=>{if(view==='assembled'){const extra=id.startsWith('Simbolo-');state=sanitize({...state,[extra?'extraX':'x']:state[extra?'extraX':'x']+dx,[extra?'extraY':'y']:state[extra?'extraY':'y']+dy});clearTimeout(timer);rebuild();paintControls();return;}const source=mountParts.find(p=>p.id===id),placed=shown.find(p=>p.id===id);if(!source||!placed)return;const at=currentPlacement(placed,source,plate);pinned[id]={...at,x:at.x+dx,y:at.y+dy};display();}});
const controls=el('div');shell.panel.append(controls,panelFooter());
const exports:HTMLButtonElement[]=[];
const M=await loadManifold(wasmUrl);
try{await document.fonts.load('120px Pacifico');}catch{/* font di sistema */}
let timer:ReturnType<typeof setTimeout>;
function set<K extends keyof Params>(key:K,value:Params[K]){state=sanitize({...state,[key]:value});clearTimeout(timer);exports.forEach(b=>b.disabled=true);timer=setTimeout(rebuild,200);}
function field(label:string,key:'text'|'initial'|'number'|'team'|'qrText'|'qrSecret') {const input=el('input',{class:'bdl-text-input',type:key==='qrSecret'?'password':'text',value:state[key],maxlength:key==='qrText'?300:24,'aria-label':label,onInput:()=>set(key,input.value)});return el('div',{class:'bdl-row'},el('label',{},label,input));}
function paintControls(){controls.replaceChildren();
 controls.append(section('Il tuo modello',segmented({label:'Modello',value:state.model,options:[{value:'name',label:'Nome'},{value:'initial',label:'Iniziale'},{value:'svg',label:'SVG'},{value:'qr',label:'QR'},{value:'jersey',label:'Maglia'},{value:'music',label:'Musica'}],onChange:v=>{const presets={name:[70,38],initial:[50,50],svg:[55,45],qr:[45,45],jersey:[45,60],music:[85,25]};const dims=presets[v];state.width=dims[0];state.depth=dims[1];state.x=0;state.y=0;state.angle=0;if(v==='jersey')state.font='sans';pinned={};set('model',v);if(v==='qr'){state.baseColor='#ffffff';state.artColor='#111111';state.shape='square';}paintControls();}}).root));
 const content=section('Personalizza');
 if(state.model==='qr')content.append(field('Testo o link del QR','qrText'),el('p',{class:'bdl-hint'},'Generato qui nel browser. Stampa la base chiara e il codice scuro.'));
 else if(state.model==='svg'||state.model==='music'){
 const input=el('input',{type:'file',accept:state.model==='music'?'.svg,.png,.jpg,.jpeg,.webp':'.svg,image/svg+xml','aria-label':'Carica SVG o codice musicale',onChange:async()=>{try{const f=input.files?.[0];if(!f)return;if(f.size>10_000_000)throw new Error('SVG troppo grande: massimo 10 MB.');uploaded=state.model==='music'?await importArtwork(f,180):parseSvg(await f.text(),f.name);rebuild();}catch(e){parts=[];exports.forEach(b=>b.disabled=true);shell.setStatus(String(e),'warn');}}});
 content.append(input,el('p',{class:'bdl-hint'},state.model==='music'?'Carica un codice Spotify già creato, in SVG o immagine. Il link Spotify da solo non genera il codice musicale.':'Logo o disegno SVG. La sagoma richiede una forma piena e connessa.'));
 if(state.model==='music'){const cover=el('input',{type:'file',accept:'.svg,.png,.jpg,.jpeg,.webp','aria-label':'Copertina in un colore',onChange:async()=>{try{const f=cover.files?.[0];if(f){uploadedCover=await importArtwork(f,180);rebuild();}}catch(e){toast(String(e));}}});content.append(el('p',{class:'bdl-hint'},'Copertina facoltativa, convertita in un colore.'),cover,button({label:'Rimuovi copertina',onClick:()=>{uploadedCover=undefined;rebuild();}}));}
 }else{content.append(field('Nome','text'));if(state.model==='initial')content.append(field('Iniziale','initial'));if(state.model==='jersey')content.append(field('Numero','number'),field('Squadra','team'));
 content.append(segmented({label:'Carattere',value:state.font,options:[{value:'cursive',label:'Corsivo'},{value:'sans',label:'Moderno'},{value:'serif',label:'Classico'}],onChange:v=>set('font',v)}).root);
 }
 {
 const extraInput=el('input',{type:'file',accept:'.svg,image/svg+xml','aria-label':'SVG aggiuntivo',onChange:async()=>{try{const f=extraInput.files?.[0];if(f){if(f.size>10_000_000)throw new Error('SVG troppo grande');extraArtwork=parseSvg(await f.text(),f.name);if(state.model!=='name'){state.extraX=state.width*(state.model==='qr'?.4:.35);state.extraY=0;state.extraSize=Math.min(12,state.width*(state.model==='qr'?.12:.2));}paintControls();rebuild();}}catch(e){toast(String(e));}}});content.append(el('p',{class:'bdl-hint'},'Aggiungi un SVG o un’icona. Trascina il simbolo nella vista Compatto, preferibilmente dall’alto, oppure usa i controlli di posizione.'),extraInput);
 const icons=el('div',{class:'bdl-key-icon-grid'});for(const icon of KEY_ICONS)icons.append(button({label:icon[1],icon:keyIconSvg(icon[3]),onClick:()=>{const artwork=parseSvg(keyIconSvg(icon[3]).replace('currentColor','#000'),icon[1]);extraArtwork=artwork;if(state.model!=='name'){state.extraX=state.width*(state.model==='qr'?.4:.35);state.extraY=0;state.extraSize=Math.min(12,state.width*(state.model==='qr'?.12:.2));}paintControls();rebuild();}}));content.append(el('details',{},el('summary',{},'Scegli un’icona'),icons));
 }
 controls.append(content);
 if(extraArtwork){const extraControls=section('Posizione del simbolo',el('p',{},extraArtwork.name??'Simbolo'),button({label:'Rimuovi simbolo',onClick:()=>{extraArtwork=undefined;paintControls();rebuild();}}));for(const [key,label,min,max]of [['extraX','Posizione orizzontale',-180,180],['extraY','Posizione verticale',-120,120],['extraSize','Dimensione simbolo',3,80],['extraAngle','Rotazione simbolo',-180,180]] as const)extraControls.append(slider({label,min,max,value:state[key],unit:key==='extraAngle'?'°':'mm',onInput:v=>set(key,v)}).root);extraControls.append(colorPicker({label:'Colore simbolo',value:state.extraColor,onChange:v=>set('extraColor',v)}).root);controls.append(extraControls);}
 if(state.model==='qr'){const qrControls=section('QR personalizzato',segmented({label:'Contenuto',value:state.qrType,options:[{value:'url',label:'Link'},{value:'text',label:'Testo'},{value:'phone',label:'Telefono'},{value:'email',label:'Email'},{value:'wifi',label:'Wi-Fi'}],onChange:v=>{set('qrType',v);paintControls();}}).root);if(state.qrType==='wifi')qrControls.append(field('Password Wi-Fi','qrSecret'));for(const [key,label,min,max]of [['qrSize','Dimensione QR',20,90],['qrX','Posizione QR orizzontale',-80,80],['qrY','Posizione QR verticale',-80,80],['qrAngle','Rotazione QR',-180,180]] as const)qrControls.append(slider({label,min,max,value:state[key],unit:key==='qrSize'?'%':key==='qrAngle'?'°':'mm',onInput:v=>set(key,v)}).root);qrControls.append(el('p',{class:'bdl-hint'},'Il margine libero del QR deve rimanere dentro la base. Posiziona SVG e icone fuori dal codice. La password Wi-Fi non viene salvata nel link.'));controls.append(qrControls);}

 const measures=section('Forma e misure');
 if(['initial','svg','qr'].includes(state.model))measures.append(segmented({label:'Sagoma',value:state.shape,options:[{value:'square',label:'Targhetta'},{value:'round',label:'Tonda'},...(state.model==='qr'?[{value:'oval',label:'Ovale'},{value:'hex',label:'Esagono'},{value:'heart',label:'Cuore'}]:[{value:'svg',label:state.model==='initial'?'Lettera':'Dal disegno'}])],onChange:v=>{if(state.model==='qr'){state.qrSize=v==='heart'?35:60;state.qrY=v==='heart'?-state.depth*.06:0;state.qrX=0;state.qrAngle=0;}set('shape',v as Params['shape']);paintControls();}}).root);
 measures.append(toggle({label:'Foro portachiavi',value:state.loop,onChange:v=>set('loop',v)}).root,segmented({label:'Posizione anello',value:state.ringType,options:[{value:'external',label:'Esterno alla base'},{value:'internal',label:'Dentro la base'}],onChange:v=>set('ringType',v)}).root);
 for(const [key,label,min,max,step]of [['width','Larghezza',25,180,1],['depth','Altezza',25,120,1],['thickness','Spessore base',2,8,.2],['hole','Foro anello',2,8,.2],['border','Bordo del nome',1,8,.2]] as const)if(key!=='border'||state.model==='name')measures.append(slider({label,min,max,step,value:state[key],unit:'mm',onInput:v=>set(key,v)}).root);
 if(state.model==='jersey'){
 const details=section('Disegno della divisa',segmented({label:'Motivo',value:state.jerseyPattern,options:[{value:'solid',label:'Tinta unita'},{value:'vertical',label:'Strisce verticali'},{value:'horizontal',label:'Strisce orizzontali'},{value:'half',label:'Metà e metà'},{value:'diagonal',label:'Diagonali'},{value:'broad',label:'Fascia centrale'},{value:'sides',label:'Strisce laterali'}],onChange:v=>set('jerseyPattern',v)}).root);
 for(const [key,label]of [['collar','Colletto'],['shirtBorder','Bordo della maglia'],['textOutline','Contorno delle scritte'],['sleevesPattern','Motivo sulle maniche'],['loop','Anello portachiavi']] as const)details.append(toggle({label,value:state[key],onChange:v=>set(key,v)}).root);
 for(const [key,label,min,max,step]of [['stripeWidth','Larghezza strisce',1,25,.5],['stripeGap','Spazio fra le strisce',1,25,.5],['stripeOffset','Sposta le strisce',-40,40,.5],['edgeWidth','Spessore bordo',.4,3,.2],['collarWidth','Spessore colletto',.5,5,.5],['outlineWidth','Spessore contorno scritte',.2,2,.1],['ringWall','Parete dell’anello',1,5,.5]] as const)details.append(slider({label,min,max,step,value:state[key],unit:'mm',onInput:v=>set(key,v)}).root);
 controls.append(details);
 const positions=section('Dimensioni e posizione delle scritte');
 for(const [key,label,min,max]of [['nameSize','Altezza nome',2,20],['numberSize','Altezza numero',5,45],['teamSize','Altezza squadra',2,20],['nameY','Posizione nome',-45,45],['numberY','Posizione numero',-45,45],['teamY','Posizione squadra',-45,45]] as const)positions.append(slider({label,min,max,value:state[key],unit:key.endsWith('Y')?'%':'mm',onInput:v=>set(key,v)}).root);
 controls.append(positions,section('Colori della divisa',...([['patternColor','Motivo'],['collarColor','Colletto'],['edgeColor','Bordo'],['outlineColor','Contorno scritte']] as const).map(([key,label])=>colorPicker({label,value:state[key],onChange:v=>set(key,v)}).root)));
 }
 controls.append(measures,section('Piatto di stampa',segmented({value:String(plateSize),options:[{value:'180',label:'180 mm'},{value:'220',label:'220 mm'},{value:'256',label:'256 mm'}],onChange:v=>{plateSize=Number(v);pinned={};display();}}).root,el('p',{class:'bdl-hint'},'I rilievi separati ricevono una sede di montaggio di 0,25 mm. Nella vista Pezzi sul piatto puoi trascinare gli oggetti. I pezzi che non entrano passano al piatto successivo.')));
 if(state.model!=='qr')controls.append(section('Decorazione',segmented({label:'Tecnica',value:state.mode,options:[{value:'relief',label:'Rilievo'},{value:'inlay',label:'Intarsio'},{value:'engrave',label:'Incisione'}],onChange:v=>set('mode',v)}).root,
 slider({label:'Gioco per intarsi separati',min:0,max:.4,step:.05,value:state.clearance,unit:'mm',hint:'0 per stampa multicolore; aumenta leggermente per inserire i pezzi dopo la stampa.',onInput:v=>set('clearance',v)}).root,
 slider({label:'Spessore decorazione',min:.4,max:2,step:.2,value:state.relief,unit:'mm',onInput:v=>set('relief',v)}).root,
 ...(['name','initial','svg'].includes(state.model)?[
 slider({label:'Dimensione disegno',min:10,max:100,value:state.scale,unit:'%',onInput:v=>set('scale',v)}).root,
 slider({label:'Sposta a destra / sinistra',min:-90,max:90,value:state.x,unit:'mm',onInput:v=>set('x',v)}).root,
 slider({label:'Sposta in alto / basso',min:-60,max:60,value:state.y,unit:'mm',onInput:v=>set('y',v)}).root,
 slider({label:'Rotazione',min:-180,max:180,value:state.angle,unit:'°',onInput:v=>set('angle',v)}).root]:[])));
 controls.append(section('Colori',state.model==='initial'?colorPicker({label:'Iniziale',value:state.initialColor,onChange:v=>set('initialColor',v)}).root:null,colorPicker({label:'Base',value:state.baseColor,onChange:v=>set('baseColor',v)}).root,colorPicker({label:'Decorazione',value:state.artColor,onChange:v=>set('artColor',v)}).root));
}
const plateLabel=el('span');const plateTools=el('div',{class:'bdl-plate-controls'});
function display(refit=false){const packed=arrange(mountParts,plateSize,plateSize,pinned);plate=Math.min(plate,Math.max(0,packed.plates.length-1));shown=view==='assembled'?parts:packed.plates[plate]??[];viewer.setMoveEnabled(true);viewer.setParts(shown,{refit});viewer.setPlateSize(plateSize,plateSize);plateTools.hidden=view==='assembled';plateLabel.textContent=view==='assembled'?'':`Piatto ${plate+1} / ${packed.plates.length}`;if(packed.oversized.length||packed.warnings.length)shell.setStatus(packed.warnings.join(' ')||'Alcuni pezzi superano il piatto.','warn');}
shell.stageTools.append(iconButton({label:'Vista 3D',icon:ICONS.iso,onClick:()=>viewer.setView('iso')}),iconButton({label:'Vista dall’alto',icon:ICONS.top,onClick:()=>viewer.setView('top')}),segmented({value:view,options:[{value:'assembled',label:'Compatto'},{value:'separate',label:'Pezzi sul piatto'}],onChange:v=>{view=v;display(true);}}).root,plateTools);
plateTools.append(button({label:'‹',title:'Piatto precedente',onClick:()=>{plate=Math.max(0,plate-1);display(true);}}),plateLabel,button({label:'›',title:'Piatto successivo',onClick:()=>{plate++;display(true);}}),button({label:'Disponi automaticamente',onClick:()=>{pinned={};display();}}));
const file=()=>slug('portachiavi-'+state.model+'-'+state.text);
function exportPacked(){const packed=arrange(mountParts,plateSize,plateSize,pinned);if(packed.oversized.length||packed.warnings.length){toast(packed.warnings[0]||'Riduci le misure: un pezzo supera il piatto.');return;}download(zipSync(Object.fromEntries(packed.plates.map((p,i)=>[`piatto-${i+1}.3mf`,to3MF(p,{title:file(),plateCenter:[plateSize/2,plateSize/2]})]))),file()+'-piatti.zip');}
for(const o of [{label:'STL',onClick:()=>download(toSTL(parts),file()+'.stl')},{label:'3MF a colori',onClick:()=>download(to3MF(parts,{title:file()}),file()+'.3mf')},{label:'Pezzi separati',onClick:exportPacked},{label:'Pezzo selezionato',onClick:()=>{const p=mountParts.find(p=>p.id===selected);if(!p){toast('Clicca prima un pezzo nell’anteprima.');return;}download(toSTL(packPlates([p],256,256).plates.flat()),slug(p.name)+'.stl');}}]){const b=button(o);b.disabled=true;exports.push(b);shell.exportBar.append(b);}
function qrPayload(){const escape=(v:string)=>v.replace(/[\\;,:"]/g,c=>'\\'+c);if(state.qrType==='phone')return 'tel:'+state.qrText;if(state.qrType==='email')return 'mailto:'+state.qrText;if(state.qrType==='wifi')return `WIFI:T:WPA;S:${escape(state.qrText)};P:${escape(state.qrSecret)};;`;return state.qrText;}
function rebuild(){try{
 const d:Design={extra:extraArtwork};if(state.model==='qr'){const q=qrArtwork(qrPayload());d.main=q.artwork;d.qrModules=q.modules;}else if(state.model==='svg'||state.model==='music'){d.main=uploaded;d.cover=uploadedCover;}else{d.main=lettering(state.text,state.font);if(state.model==='initial')d.initial=lettering(state.initial,'serif');if(state.model==='jersey'){d.main=state.text.trim()?lettering(state.text,state.font):undefined;d.team=state.team.trim()?lettering(state.team,'sans'):undefined;d.number=state.number.trim()?lettering(state.number,'sans'):undefined;}}
 if((state.model==='svg'||state.model==='music')&&!d.main&&!d.extra)throw new Error('Carica un file oppure aggiungi un’icona.');
 const result=build(M,state,d);const seated=assemblySeats(M,result.parts);parts=result.parts;mountParts=seated;lastValid={...state};display();exports.forEach(b=>b.disabled=false);writeHashState({...state,qrSecret:''},DEFAULTS);const b=bounds(parts);const placementWarnings=arrange(mountParts,plateSize,plateSize,pinned).warnings;const warnings=[...result.warnings,...placementWarnings];shell.setStatus(warnings.join(' ')||`${(b.max[0]-b.min[0]).toFixed(1)} × ${(b.max[1]-b.min[1]).toFixed(1)} mm · ${parts.length} pezzi`,warnings.length?'warn':'ok');
 }catch(e){if(parts.length){state={...lastValid};paintControls();}display();exports.forEach(b=>b.disabled=true);shell.setStatus(e instanceof Error?e.message:String(e),'warn');}}
paintControls();rebuild();
