import '@bdl/ui-kit/style.css';
import {bounds,type Part} from '@bdl/geometry';
import {createViewer} from '@bdl/viewer';
import {toSTL,to3MF,download,slug} from '@bdl/export';
import {zipSync} from 'fflate';
import {appShell,section,slider,colorPicker,button,iconButton,panelFooter,readHashState,writeHashState,ICONS,el,segmented,toast,toggle} from '@bdl/ui-kit';
import {parseSvg,type SvgArtwork} from '../../coaster/src/svg.ts';
import {lettering} from '../../keychain/src/artwork.ts';
import {KEY_ICONS,keyIconSvg} from '../../keycap/src/icons.ts';
import {arrange,currentPlacement,type Placements} from '../../box/src/placement.ts';
import type {Design} from './geometry.ts';
import {DEFAULTS,sanitize,type Params} from './params.ts';
import {capabilities,positionDraft,changeModel,type PositionDraft} from './interaction.ts';
const shell=appShell({title:'Natale',intro:'Piccole decorazioni, grandi ricordi. Crea palline e ornamenti da regalare.'});
let state=sanitize(readHashState(DEFAULTS)),extra:SvgArtwork|undefined,parts:Part[]=[],mounted:Part[]=[],shown:Part[]=[],view='assembled',plate=0,plateSize=256,selected:string|null=null,pinned:Placements={},lastValid={...state};
const drafts:Partial<Record<Params['model'],PositionDraft>>={},layouts:Partial<Record<Params['model'],Placements>>={};
let revision=0,busy=false,dragging=false,held:WorkerReply|undefined,queued:BuildRequest|undefined;
type BuildRequest={id:number;state:Params;design:Design};
type WorkerReply={id:number;ok:boolean;parts:Part[];mounted:Part[];warnings:string[];adjustments?:{x?:number;y?:number};error?:string};
const worker=new Worker(new URL('./worker.ts',import.meta.url),{type:'module'});
const viewer=createViewer(shell.stage,{smoothView:true,dragGroup:id=>view==='assembled'?(id.startsWith('text-')?'text-':id.startsWith('symbol-')?'symbol-':id):id,onDragState:active=>{dragging=active;if(!active&&held){const reply=held;held=undefined;receive(reply);}},fitPlate:()=>view!=='assembled',movePlane:()=>view==='assembled'&&state.model==='sphere'?'xz':'xy',canMovePart:id=>view!=='assembled'||id.startsWith('text-')||id.startsWith('symbol-'),onSelectPart:id=>{selected=id;refreshActions();},onMovePart:(id,dx,dy)=>{if(view==='assembled'){const symbol=id.startsWith('symbol-');state=sanitize({...state,[symbol?'extraX':'x']:state[symbol?'extraX':'x']+dx,[symbol?'extraY':'y']:state[symbol?'extraY':'y']+dy});revision++;clearTimeout(timer);rebuild();paint();}else{const source=mounted.find(p=>p.id===id),placed=shown.find(p=>p.id===id);if(source&&placed){const at=currentPlacement(placed,source,plate);pinned[id]={...at,x:at.x+dx,y:at.y+dy};display();}}}});
const controls=el('div',{class:'bdl-christmas-controls'});shell.panel.append(controls,panelFooter());const exports:HTMLButtonElement[]=[];try{await document.fonts.load('120px Pacifico');}catch{/* carattere di sistema */}let timer:ReturnType<typeof setTimeout>;
function set<K extends keyof Params>(k:K,v:Params[K]){state=sanitize({...state,[k]:v});revision++;exports.forEach(b=>b.disabled=true);clearTimeout(timer);timer=setTimeout(rebuild,state.model==='sphere'?140:80);}
function range(key:keyof Params,label:string,min:number,max:number,step=1,unit='mm'){return slider({label,min,max,step,value:state[key] as number,unit,onInput:v=>set(key,v)}).root;}
function paint(){const open=new Set([...controls.querySelectorAll<HTMLDetailsElement>('details[open]')].map(d=>d.dataset.section));const scroll=shell.panel.scrollTop,active=document.activeElement as HTMLInputElement|null,label=active?.getAttribute('aria-label'),caret=active?.selectionStart;const c=capabilities(state,!!extra);controls.replaceChildren();controls.append(section('Il tuo ornamento',segmented({label:'Modello',value:state.model,options:[{value:'flat',label:'Ornamento piatto'},{value:'sphere',label:'Pallina sferica'}],onChange:v=>{drafts[state.model]=positionDraft(state);layouts[state.model]=pinned;state=changeModel(state,v as Params['model'],drafts[v as Params['model']]);pinned=layouts[state.model]??{};selected=null;revision++;clearTimeout(timer);rebuild();paint();}}).root));
 if(state.model==='flat'){const shapes=section('Forma',segmented({label:'Sagoma',value:state.shape,options:[{value:'bauble',label:'Pallina'},{value:'tree',label:'Alberello'},{value:'star',label:'Stella'},{value:'snowflake',label:'Fiocco di neve'},{value:'heart',label:'Cuore'},{value:'bell',label:'Campanella'},{value:'gingerbread',label:'Omino'}],onChange:v=>{set('shape',v);paint();}}).root,state.shape==='snowflake'?null:segmented({label:'Stile',value:state.style,options:[{value:'solid',label:'Pieno'},{value:'outline',label:'Cornice'},{value:'snow',label:'Traforato'}],onChange:v=>set('style',v)}).root);shapes.querySelector('[aria-label="Sagoma"]')?.parentElement?.classList.add('bdl-seg-wrap');controls.append(shapes);}
 else controls.append(section('La tua pallina',segmented({label:'Superficie',value:state.profile,options:[{value:'smooth',label:'Liscia'},{value:'wave',label:'A onda'},{value:'spiral',label:'Spirale'}],onChange:v=>{set('profile',v);paint();}}).root,...(state.profile==='smooth'?[]:[range('ribs','Numero di coste',6,24,2,''),...(state.profile==='wave'?[range('twist','Torsione',0,300,10,'°')]:[])]),el('p',{class:'bdl-hint'},'Guscio cavo in due metà con incastro, senza viti. Il numero di coste resta automaticamente pari.')));
 const name=el('input',{class:'bdl-text-input',type:'text',value:state.text,maxlength:32,'aria-label':'Nome o augurio',placeholder:'Nome, anno, augurio…',onInput:()=>{const before=!!state.text.trim();set('text',name.value);if(before!==!!state.text.trim())paint();}});
 const personal=section('Personalizza',el('div',{class:'bdl-row'},el('label',{},'Nome o augurio',name)),el('p',{class:'bdl-hint'},'Lascia vuoto per un ornamento senza scritte. Testo, SVG e icone possono stare insieme.'),c.text?segmented({label:'Carattere',value:state.font,options:[{value:'cursive',label:'Corsivo'},{value:'sans',label:'Moderno'},{value:'serif',label:'Classico'}],onChange:v=>set('font',v)}).root:null);
 if(state.model==='flat'&&c.text)personal.append(toggle({label:'Scritta dentro la sagoma',value:state.containText,onChange:v=>set('containText',v)}).root,el('p',{class:'bdl-hint'},'Attivo: adatta tutta la scritta al bordo. Disattivo: puoi farla uscire dalla sagoma.'));
 const file=el('input',{type:'file',accept:'.svg,image/svg+xml','aria-label':'Aggiungi SVG',onChange:async()=>{try{const f=file.files?.[0];if(!f)return;if(f.size>10_000_000)throw new Error('SVG troppo grande: massimo 10 MB.');const next=parseSvg(await f.text(),f.name);extra=next;revision++;paint();rebuild();}catch(e){toast(String(e));}}});personal.append(file);
 const icons=el('div',{class:'bdl-key-icon-grid'});for(const icon of KEY_ICONS)icons.append(button({label:icon[1],icon:keyIconSvg(icon[3]),onClick:()=>{extra=parseSvg(keyIconSvg(icon[3]).replace('currentColor','#000'),icon[1]);revision++;paint();rebuild();}}));personal.append(el('details',{'data-section':'icons'},el('summary',{},'Scegli un’icona'),icons));
 if(extra)personal.append(el('p',{},extra.name??'Simbolo'),button({label:'Rimuovi simbolo',onClick:()=>{extra=undefined;revision++;paint();rebuild();}}));personal.append(el('p',{class:'bdl-hint'},state.model==='flat'?'Trascina scritte e simboli nella vista dall’alto.':'Trascina scritte e simboli nella vista frontale. Le scritte seguono la superficie della pallina.'));controls.append(personal);
 const dimensions=section('Dimensioni',range('size','Dimensione',35,160),state.model==='flat'?range('thickness','Spessore',2,6,.2):range('wall','Parete',1.2,3,.2),toggle({label:'Anello per appendere',value:state.loop,onChange:v=>{set('loop',v);paint();}}).root,state.loop?range('hole','Foro del filo',2,7,.5):null);controls.append(dimensions);
 const details=el('details',{'data-section':'advanced'},el('summary',{},'Personalizzazione avanzata'));
 if(c.decoration)details.append(section('Finitura',segmented({label:'Tecnica',value:state.mode,options:[{value:'relief',label:'Rilievo'},{value:'inlay',label:'Intarsio'},{value:'engrave',label:'Incisione'}],onChange:v=>{set('mode',v);paint();}}).root,c.depth?range('relief',state.mode==='engrave'?'Profondità incisione':state.mode==='inlay'?'Profondità intarsio':'Altezza rilievo',.4,state.model==='flat'?Math.min(1.6,state.thickness-.8):Math.min(1.6,state.wall*.6),.1):null));
 if(c.text)details.append(section('Scritta',range('scale','Dimensione scritta',20,100,1,'%'),range('x','Destra / sinistra',-80,80),range('y','Alto / basso',-80,80),range('angle','Rotazione scritta',-180,180,1,'°')));
 if(extra)details.append(section('Simbolo',range('extraX','Simbolo: destra / sinistra',-80,80),range('extraY','Simbolo: alto / basso',-80,80),range('extraSize','Dimensione simbolo',5,60),range('extraAngle','Rotazione simbolo',-180,180,1,'°')));
 if(state.model==='sphere')details.append(range('clearance','Gioco dell’incastro',.05,.3,.05));if(c.decoration||state.model==='sphere')controls.append(details);
 controls.append(section('Colori',colorPicker({label:'Ornamento',value:state.baseColor,onChange:v=>set('baseColor',v)}).root,c.text&&c.colors?colorPicker({label:'Scritta',value:state.artColor,onChange:v=>set('artColor',v)}).root:null,extra&&c.colors?colorPicker({label:'Simbolo',value:state.extraColor,onChange:v=>set('extraColor',v)}).root:null),section('Piatto di stampa',segmented({value:String(plateSize),options:[{value:'180',label:'180 mm'},{value:'220',label:'220 mm'},{value:'256',label:'256 mm'}],onChange:v=>{plateSize=Number(v);pinned={};display();}}).root,el('p',{class:'bdl-hint'},'Pezzi separabili con sedi di montaggio. Trascinali sul piatto; quando non entrano, vengono aggiunti altri piatti. Testo, simboli e impostazioni restano memorizzati quando cambi modello. Gli SVG restano in questa sessione.')));
 for(const d of controls.querySelectorAll<HTMLDetailsElement>('details'))d.open=open.has(d.dataset.section);
 if(label&&active?.tagName==='INPUT'){const replacement=[...controls.querySelectorAll<HTMLInputElement>('input')].find(i=>i.getAttribute('aria-label')===label);replacement?.focus({preventScroll:true});if(replacement?.type==='text'&&caret!==null&&caret!==undefined)replacement.setSelectionRange(caret,caret);}
 shell.panel.scrollTop=scroll;

}
const viewControl=segmented({value:view,options:[{value:'assembled',label:'Compatto'},{value:'separate',label:'Pezzi sul piatto'}],onChange:v=>{view=v;display(true);viewer.setView(v==='separate'?'top':state.model==='sphere'?'front':'iso');}});
const viewSwitch=viewControl.root;
const plateTools=el('div',{class:'bdl-plate-controls'}),plateLabel=el('span');
function display(refit=false){if(mounted.length<2)view='assembled';viewControl.set(view);viewSwitch.hidden=mounted.length<2;const packed=arrange(mounted,plateSize,plateSize,pinned);plate=Math.min(plate,Math.max(0,packed.plates.length-1));shown=view==='assembled'?parts:packed.plates[plate]??[];viewer.setMoveEnabled(true);viewer.setParts(shown,{refit});viewer.setPlateSize(plateSize,plateSize);plateTools.hidden=view==='assembled';refreshActions();plateLabel.textContent=`Piatto ${plate+1} / ${packed.plates.length}`;if(packed.warnings.length||packed.oversized.length)shell.setStatus(packed.warnings.join(' ')||'Un pezzo supera il piatto: riduci la dimensione.','warn');}
shell.stageTools.append(iconButton({label:'Vista 3D',icon:ICONS.iso,onClick:()=>viewer.setView('iso')}),iconButton({label:'Vista di personalizzazione',icon:ICONS.top,onClick:()=>viewer.setView(state.model==='sphere'?'front':'top')}),viewSwitch,plateTools);
plateTools.append(button({label:'‹',title:'Piatto precedente',onClick:()=>{plate=Math.max(0,plate-1);display(true);}}),plateLabel,button({label:'›',title:'Piatto successivo',onClick:()=>{plate++;display(true);}}),button({label:'Disponi automaticamente',onClick:()=>{pinned={};display();}}));
const filename=()=>slug('natale-'+(state.model==='sphere'?state.profile:state.shape)+'-'+state.text);
function packedExport(){const packed=arrange(mounted,plateSize,plateSize,pinned);if(packed.warnings.length||packed.oversized.length){toast(packed.warnings[0]||'Un pezzo supera il piatto.');return;}download(zipSync(Object.fromEntries(packed.plates.map((p,i)=>[`piatto-${i+1}.3mf`,to3MF(p,{title:filename(),plateCenter:[plateSize/2,plateSize/2]})]))),filename()+'-piatti.zip');}
for(const o of [{label:'STL',onClick:()=>download(toSTL(parts),filename()+'.stl')},{label:'3MF a colori',onClick:()=>download(to3MF(parts,{title:filename()}),filename()+'.3mf')},{label:'Pezzi separati',onClick:packedExport},{label:'Pezzo selezionato',onClick:()=>{const p=mounted.find(p=>p.id===selected);if(!p){toast('Seleziona prima un pezzo.');return;}const packed=arrange([p],plateSize,plateSize,{});if(packed.oversized.length){toast('Il pezzo supera il piatto.');return;}download(toSTL(packed.plates.flat()),slug(p.name)+'.stl');}}]){const b=button(o);b.disabled=true;exports.push(b);shell.exportBar.append(b);}
function refreshActions(){if(exports[2])exports[2].hidden=mounted.length<2;if(exports[3])exports[3].hidden=!selected||!mounted.some(p=>p.id===selected);}
let cachedText='',cachedFont='',cachedArtwork:SvgArtwork|undefined;
function send(request:BuildRequest){busy=true;worker.postMessage(request);}
function rebuild(){
 exports.forEach(b=>b.disabled=true);shell.stage.setAttribute('aria-busy','true');shell.setStatus('La tua creazione prende forma…','busy');
 try{if(state.text.trim()&&(cachedText!==state.text||cachedFont!==state.font)){cachedArtwork=lettering(state.text,state.font);cachedText=state.text;cachedFont=state.font;}
 const request={id:revision,state:{...state},design:{text:state.text.trim()?cachedArtwork:undefined,extra}};
 if(busy)queued=request;else send(request);
 }catch(e){shell.stage.setAttribute('aria-busy','false');shell.setStatus(e instanceof Error?e.message:String(e),'warn');}
}
function receive(reply:WorkerReply){
 if(reply.id!==revision)return;
 if(dragging){held=reply;return;}
 shell.stage.setAttribute('aria-busy','false');
 if(!reply.ok){shell.setStatus(reply.error??'Modifica la posizione della decorazione.','warn');return;}
 const changed=state.model!==lastValid.model;if(reply.adjustments){state=sanitize({...state,...reply.adjustments});if(Object.keys(reply.adjustments).length)paint();}parts=reply.parts;mounted=reply.mounted;lastValid={...state};if(!mounted.some(p=>p.id===selected))selected=null;
 writeHashState(state,DEFAULTS);exports.forEach(b=>b.disabled=false);display(changed);if(changed)viewer.setView(state.model==='sphere'?'front':'top');
 const packed=arrange(mounted,plateSize,plateSize,pinned),b=bounds(parts),messages=[...reply.warnings,...packed.warnings,...(packed.oversized.length?['Un pezzo supera il piatto: scegli un piatto più grande o riduci la misura.']:[])];
 shell.setStatus(messages.join(' ')||`${(b.max[0]-b.min[0]).toFixed(1)} × ${(b.max[1]-b.min[1]).toFixed(1)} mm · ${parts.length} ${parts.length===1?'pezzo':'pezzi'}`,messages.length?'warn':'ok');
}
worker.onmessage=(event:MessageEvent<WorkerReply>)=>{busy=false;receive(event.data);if(queued){const latest=queued;queued=undefined;if(latest.id===revision)send(latest);}};
worker.onerror=()=>{busy=false;queued=undefined;shell.stage.setAttribute('aria-busy','false');shell.setStatus('Anteprima non disponibile. Ricarica la pagina: il link conserva l’ultima configurazione valida.','warn');};
plateTools.hidden=true;viewSwitch.hidden=true;refreshActions();paint();rebuild();
