import '@bdl/ui-kit/style.css';
import {appShell,section,el,button,slider,segmented,toggle,toast,ICONS} from '@bdl/ui-kit';
import {download} from '@bdl/export';
import {parseSvg} from '../../coaster/src/svg.ts';
import {SVG_TARGETS,sendSvg} from '../../shared/svg-transfer.ts';
import type {Options} from './trace.ts';
const shell=appShell({title:'Immagine → SVG',intro:'Dall’immagine al tuo prossimo oggetto. Converti, guarda l’anteprima e scegli dove usarla.'});
shell.stage.setAttribute('aria-label','Anteprima conversione');
let options:Options={mode:'mono',threshold:180,colors:4,cleanup:3,invert:false,background:false};
let source:ImageBitmap|undefined,name='disegno',resolution=192,version=0,loadVersion=0,svg='',originalUrl='',vectorUrl='',timer:ReturnType<typeof setTimeout>;
const worker=new Worker(new URL('./worker.ts',import.meta.url),{type:'module'});
const original=el('img',{alt:'Immagine originale'}),vector=el('img',{alt:'Anteprima dei tracciati SVG'});
const preview=el('div',{class:'bdl-vector-preview'},el('figure',{},el('figcaption',{},'Originale'),original),el('figure',{},el('figcaption',{},'SVG · tracciati pieni'),vector));shell.stage.append(preview);
const file=el('input',{type:'file',accept:'.png,.jpg,.jpeg,.webp,image/png,image/jpeg,image/webp',class:'bdl-input','aria-label':'Carica immagine'});
const filename=el('p',{class:'bdl-hint'},'PNG, JPG o WebP · massimo 10 MB');
const mono=el('div'),colors=slider({label:'Colori',min:2,max:8,value:4,onInput:v=>{options.colors=v;schedule();}});
mono.append(slider({label:'Soglia',min:1,max:254,value:180,onInput:v=>{options.threshold=v;schedule();}}).root,toggle({label:'Inverti chiaro e scuro',value:false,onChange:v=>{options.invert=v;schedule();}}).root);
colors.root.hidden=true;
const target=el('select',{class:'bdl-select','aria-label':'Generatore di destinazione'},...SVG_TARGETS.map(([id,label])=>el('option',{value:id},label)));
const save=button({label:'Scarica SVG',icon:ICONS.download,variant:'primary',onClick:()=>download(new TextEncoder().encode(svg),name+'.svg','image/svg+xml')});
const use=button({label:'Usa in un generatore',icon:ICONS.link,variant:'primary',onClick:()=>{try{sendSvg(svg,name+'.svg',target.value);}catch(e){toast('Il browser non permette il passaggio diretto. Puoi scaricare l’SVG. '+String(e));}}});
const ready=(value:boolean)=>{save.disabled=!value;use.disabled=!value;};ready(false);
shell.panel.append(section('La tua immagine',file,filename,el('p',{class:'bdl-hint'},'Il file resta sul tuo dispositivo. Loghi e disegni danno i risultati migliori; le fotografie vengono semplificate.')),section('Il tuo SVG',segmented({label:'Stile',value:'mono',options:[{value:'mono',label:'Monocolore'},{value:'color',label:'Più colori'}],onChange:v=>{options.mode=v as Options['mode'];mono.hidden=v!=='mono';colors.root.hidden=v!=='color';schedule();}}).root,mono,colors.root,slider({label:'Dettagli',min:64,max:320,step:16,value:192,hint:'Più dettagli mantengono contorni piccoli; meno dettagli alleggeriscono il disegno.',onInput:v=>{resolution=v;schedule();}}).root,slider({label:'Pulizia',min:0,max:40,value:3,hint:'Elimina le isole più piccole, senza riempire i fori.',onInput:v=>{options.cleanup=v;schedule();}}).root,toggle({label:'Rimuovi sfondo',value:false,hint:'Rimuove il colore vicino a quello dell’angolo dell’immagine. I file trasparenti conservano già lo sfondo vuoto.',onChange:v=>{options.background=v;schedule();}}).root),section('Usa il risultato',el('label',{},'Generatore di destinazione',target),use,el('p',{class:'bdl-hint'},'L’SVG viene caricato come decorazione, pronto da posizionare. I generatori usano i tracciati; scegli lì i colori di stampa. Per una sagoma servono forme connesse.')));
shell.exportBar.append(save);shell.setStatus('Carica un’immagine per iniziare');
function schedule(){clearTimeout(timer);version++;svg='';ready(false);shell.setStatus(source?'Conversione…':'Carica un’immagine per iniziare',source?'busy':'ok');if(source)timer=setTimeout(convert,140);}
function convert(){if(!source)return;const canvas=document.createElement('canvas'),scale=resolution/Math.max(source.width,source.height);canvas.width=Math.max(1,Math.round(source.width*scale));canvas.height=Math.max(1,Math.round(source.height*scale));const ctx=canvas.getContext('2d',{willReadFrequently:true})!;ctx.drawImage(source,0,0,canvas.width,canvas.height);const image=ctx.getImageData(0,0,canvas.width,canvas.height);worker.postMessage({id:version,image:{width:image.width,height:image.height,data:image.data},options});}
worker.onmessage=(event:MessageEvent<{id:number;svg?:string;points:number;paths:number;error?:string}>)=>{const result=event.data;if(result.id!==version)return;if(result.error){shell.setStatus(result.error,'warn');return;}try{parseSvg(result.svg!,name+'.svg');svg=result.svg!;if(vectorUrl)URL.revokeObjectURL(vectorUrl);vectorUrl=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));vector.src=vectorUrl;ready(true);shell.setStatus(`${result.paths} contorni · ${result.points} punti · pronto da usare`);}catch(e){shell.setStatus('Riduci i dettagli: '+String(e),'warn');}};
worker.onerror=()=>{ready(false);shell.setStatus('Conversione interrotta: ricarica la pagina.','warn');};
file.addEventListener('change',async()=>{const f=file.files?.[0];if(!f)return;const token=++loadVersion;version++;ready(false);try{if(f.size>10000000||!/^image\/(png|jpeg|webp)$/.test(f.type))throw new Error('Usa PNG, JPG o WebP fino a 10 MB.');const next=await createImageBitmap(f);if(token!==loadVersion){next.close();return;}if(next.width*next.height>40000000){next.close();throw new Error('Immagine troppo grande: ridimensionala sotto 40 megapixel.');}source?.close();source=next;name=f.name.replace(/\.[^.]+$/,'').slice(0,100)||'disegno';filename.textContent=f.name;if(originalUrl)URL.revokeObjectURL(originalUrl);originalUrl=URL.createObjectURL(f);original.src=originalUrl;schedule();}catch(e){shell.setStatus(e instanceof Error?e.message:String(e),'warn');}file.value='';});
